version: "3.9"

services:

  perlite:
    build:
        context: ./perlite
   
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash

    volumes:
      - ./Demo:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web    
    ports:
      - 80:80
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

  

